[package]
name = "luban_tauri"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = "2"

[dependencies]
anyhow.workspace = true
luban_server = { path = "../luban_server" }
open = "5"
tauri = "2"
